// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripTracker.API.DbContexts;

#nullable disable

namespace TripTracker.API.Migrations
{
    [DbContext(typeof(TripTrackerContext))]
    partial class TripTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripTracker.API.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Avontuurlijke roadtrip door West-Europa",
                            EndDate = new DateTime(2024, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Roadtrip Europa 2024",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Romantisch weekendje Parijs",
                            EndDate = new DateTime(2024, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Weekend Parijs",
                            StartDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TripTracker.API.Entities.TripStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripStops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Champ de Mars, Paris, France",
                            Country = "France",
                            DateTime = new DateTime(2024, 7, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "De iconische Eiffeltoren in Parijs",
                            Latitude = 48.858400000000003,
                            Longitude = 2.2945000000000002,
                            Title = "Eiffeltoren",
                            TripId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pariser Platz, Berlin, Germany",
                            Country = "Germany",
                            DateTime = new DateTime(2024, 7, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historisch monument in Berlijn",
                            Latitude = 52.516300000000001,
                            Longitude = 13.377700000000001,
                            Title = "Brandenburger Tor",
                            TripId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rue de Rivoli, Paris, France",
                            Country = "France",
                            DateTime = new DateTime(2024, 8, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wereldberoemd kunstmuseum met de Mona Lisa",
                            Latitude = 48.860599999999998,
                            Longitude = 2.3376000000000001,
                            Title = "Louvre Museum",
                            TripId = 2
                        });
                });

            modelBuilder.Entity("TripTracker.API.Entities.TripStop", b =>
                {
                    b.HasOne("TripTracker.API.Entities.Trip", "Trip")
                        .WithMany("TripStops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripTracker.API.Entities.Trip", b =>
                {
                    b.Navigation("TripStops");
                });
#pragma warning restore 612, 618
        }
    }
}
